version: '3'

services:
 nexus:
  image: sonatype/nexus
  container_name: nexus
  ports:
    - "8081:8081"
  networks:
    - devnet
  volumes:
    - "/opt/nexus/:/var/lib/nexus"

 jenkins:
  image: jenkins
  container_name: jenkins
  ports:
    - "8080:8080"
  networks:
    - devnet
  volumes:
    - "$PWD/jenkins:/var/jenkins_home"
